### PR TITLE
First pull request

### PR DESCRIPTION
**Pull request by andresporras3423**
* Using gradients
* Using flexbox
* Using CSS Grid
* Using float

### CODE REVIEW

**Review by fatymahmed — CHANGES_REQUESTED** [review]
## Hi @andresporras3423,
Great job so far, your project looks good 👏👏.
However, there is one thing that you need to fix so that you can meet all the requirements.
- The 4 elements above the footer which contain images should be links just like the in the apple page.

[OPTIONAL]
- I encourage you to use the `<main>` tag for the dominant content of the `<body>` of a document.

### Kindly make the suggested changes and request for another code review.
## Status: Changes Required
_Feel free to reach out to me on slack (Fatima) if you have any questions, I'd be happy to help._

**Comment by andresporras3423** [comment]
Problems solved
* Using links for the images
* Using the main tag for the dominant content

**Review by suretrust — APPROVED** [review]
Hi @andresporras3423,

### Amazing job implementing the TSEs' suggestions! 🙌 Let's get this merged. 👍 

_Good luck with your future projects and happy coding!_ 🎉

**Comment by andresporras3423** [comment]
Thanks for your feedback

**Pull request merged**
